language: rust

rust:
  - 1.40.0

branches:
  only:
  - master
  # Github release tags (for example "v0.9" or "v0.9.1").
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
  - node_modules
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - CARGO_INCREMENTAL=1
  matrix:
    - FEATURE=test

jobs:
  include:
  # Formatting & other lints that do not require compilation.
  - name: lints
    install:
    - cargo install --list
    - nvm install 8 && nvm use 8
    - npm install cspell
    - ./node_modules/.bin/cspell --version
    - npm install markdownlint-cli
    - ./node_modules/.bin/markdownlint --version
    script:
    - ./node_modules/.bin/cspell src/**/*.rs
    - ./node_modules/.bin/cspell examples/**/*.rs
    - ./node_modules/.bin/cspell tests/**/*.rs
    - find . -not -path "./node_modules/*" -not -path "./target/*" -name "*.md" | xargs ./node_modules/.bin/cspell
    - find . -not -path "./node_modules/*" -not -path "./target/*" -name "*.md" | xargs ./node_modules/.bin/markdownlint
